//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsAcountInfo
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> TravelCost { get; set; }
        public Nullable<decimal> LunchCost { get; set; }
        public Nullable<decimal> InstrumentsCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string Paid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
